# Bundler is messing with that later on
#GEM_PATH = ENV['_ORIGINAL_GEM_PATH']
GEM_PATH = ENV['GEM_PATH']


# Setup bundler environment
TOP_DIR = File.dirname(File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__)
ENV['BUNDLE_GEMFILE'] = File.join(TOP_DIR, 'Gemfile')
require 'bundler'
Bundler.setup()

require 'yaml'

desc "Call after 'bundle install --path vendor'"
task 'post-install', [:frcp_url] => [:create_omf_ec, :create_config_file]

desc "Create omf_ec"
task :create_omf_ec, :frcp_url do |t, args|
  target = 'omf_ec'
  frcp_url = args[:frcp_url] || ENV['FRCP_URL']
  unless frcp_url
    abort "Missing 'frcp_url'. Either export FRCP_URL, or call 'rake create_config_files[FRCP_URL] "
  end
  unless File.readable?("#{target}.in")
    abort "Can't find '#{target}.in' in local directory"
  end
  tmpl = File.read("#{target}.in")

  home = ENV['HOME']
  rvm_bin_path = ENV["rvm_bin_path"]
  if rvm_bin_path
    rvm_home = rvm_bin_path.match(/.*rvm/)[0]
    #gp = ENV['GEM_PATH']
    d, ruby, gemset = GEM_PATH.match(/.*(ruby.*)@(.*)/).to_a
  else
    rvm_home = ruby = gemset = ''
  end

  s = tmpl.gsub('%HOME%', home).gsub('%RVM_HOME%', rvm_home).gsub('%RUBY%', ruby).gsub('%GEMSET%', gemset).gsub('%FRCP_URL%', frcp_url)
  File.open(target, 'w') do |f|
    f.write(s)
  end
  File.chmod(0755, target)
  puts ".. Created '#{target}'."
end

desc "Create config file"
task :create_config_file, :frcp_url do |t, args|
  frcp_url = args[:frcp_url] || ENV['FRCP_URL']
  unless frcp_url
    abort "Missing 'frcp_url'. Either export FRCP_URL, or call 'rake create_config_files[FRCP_URL] "
  end
  target = 'omf_ec.yml'
  unless File.readable?("#{target}.in")
    abort "Can't find '#{target}.in' in local directory"
  end
  cfg = YAML.load_file("#{target}.in")
  cfg["communication"]["url"] = frcp_url
  File.open(target, 'w') do |f|
    f.write(cfg.to_yaml)
  end
  puts ".. Created config file '#{target}'."
end
